#! /bin/sh
#*******************************************************************************
# Written by: Joshua DeWeese(josh.deweese@gmail.com)
# please catch and release
#*******************************************************************************

# decompress index, package, and source files
for file in *.bz2
do
    bunzip2 -q $file
done

# remove .bz2 sufix from index, package, and source files that are 0 bytes
for file in *.bz2
do
    mv $file `echo $file | sed s/.bz2//`
done

